FROM golang:1.14-alpine as build-env
ENV GO111MODULE=on

WORKDIR /go/src/kumparan 
COPY . .
RUN go build main.go

FROM alpine
WORKDIR /app
COPY --from=build-env /go/src/kumparan/main /app
ENTRYPOINT [ "./main" ]