version: "3.7"
services:
    redis:
        image: "redis:alpine"
    mysql:
        image: mysql:5.7.31 
        environment: 
            MYSQL_DATABASE: "kumparan"
            MYSQL_ROOT_PASSWORD: "kumparan-test"
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        environment: 
            ALLOW_ANONYMOUS_LOGIN: "yes"
    kafka:
        image: 'bitnami/kafka:latest'
        environment: 
            KAFKA_BROKER_ID: 1
            ALLOW_PLAINTEXT_LISTENER: "yes"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENERS: "PLAINTEXT://:9092"
            # KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
        ports: 
            - "9093:9092"
        # onrun: 
        #     - bash -c "kafka-topics.sh --create --topic kumparan --bootstrap-server kafka:9092"
        depends_on: 
            - zookeeper
    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        environment: 
            - node.name=es01
            - discovery.type=single-node
        ports: 
            - 9200:9200
    migrate:
        build: 
            context: .
            dockerfile: dockerfile.migrate
    api:
        build:
            context: .
            dockerfile: dockerFile.api
        ports: 
            - "12130:12130"
    cron:
        build:
            context: .
            dockerfile: dockerfile.cron